import type { DigitalProduct } from './types';

export const digitalProducts: DigitalProduct[] = [
  { id: 'd1', slug: 'chandelier-3d', category: 'models3d', titleUk: '3D модель люстри', titleEn: 'Chandelier 3D Model', descUk: 'Повна 3D модель люстри для ЧПК та рендерингу.', descEn: 'Full 3D chandelier model for CNC and rendering.', price: 249, currency: 'UAH', previewImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80', formats: ['OBJ', 'STL', 'FBX'], fileSize: '18 MB', polygons: '124k' },
  { id: 'd2', slug: 'rose-vector', category: 'vectors', titleUk: 'Вектор троянди', titleEn: 'Rose Vector', descUk: 'Детальний вектор троянди для лазерного гравювання.', descEn: 'Detailed rose vector for laser engraving.', price: 99, currency: 'UAH', previewImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80', formats: ['SVG', 'DXF', 'AI'], fileSize: '2.4 MB', featured: true },
  { id: 'd3', slug: 'eagle-3d', category: 'models3d', titleUk: '3D модель орла', titleEn: 'Eagle 3D Model', descUk: 'Фотореалістична 3D модель орла. Ідеально для ЧПК.', descEn: 'Photorealistic eagle 3D model. Perfect for CNC.', price: 349, currency: 'UAH', previewImage: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400&q=80', formats: ['OBJ', 'STL', 'BLEND'], fileSize: '32 MB', polygons: '280k', featured: true },
  { id: 'd4', slug: 'mandala-vector', category: 'vectors', titleUk: 'Мандала вектор', titleEn: 'Mandala Vector', descUk: 'Орнаментальна мандала для ЧПК гравіювання та різьблення.', descEn: 'Ornamental mandala for CNC engraving and carving.', price: 79, currency: 'UAH', previewImage: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400&q=80', formats: ['SVG', 'DXF', 'CDR'], fileSize: '1.8 MB' },
  { id: 'd5', slug: 'shelf-3d', category: 'models3d', titleUk: '3D модель полиці', titleEn: 'Shelf 3D Model', descUk: 'Параметрична 3D модель дерев\'яної полиці. Включає технічні креслення.', descEn: 'Parametric wooden shelf 3D model with technical drawings.', price: 189, currency: 'UAH', previewImage: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&q=80', formats: ['OBJ', 'STL', 'DWG'], fileSize: '9 MB' },
  { id: 'd6', slug: 'animals-pack', category: 'vectors', titleUk: 'Пак тварин SVG', titleEn: 'Animals SVG Pack', descUk: 'Набір із 12 векторних тварин для лазерного різання та ЧПК.', descEn: 'Set of 12 animal vectors for laser cutting and CNC.', price: 199, currency: 'UAH', previewImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80', formats: ['SVG', 'DXF', 'AI'], fileSize: '5.6 MB', featured: true },
];
