import type { PortfolioItem } from './types';

export const portfolioItems: PortfolioItem[] = [
  {
    id: 'p-madonna',
    category: 'carving',
    slug: 'madonna-child-relief',
    titleUk: 'Барельєф «Благословення Мадонни»',
    titleEn: "Bas-Relief «Madonna's Blessing»",
    descUk: 'Монументальне сакральне панно за мотивами класичного Ренесансу. Багатопланова об’ємна різьба по масиву дерева в пишній бароковій акантовій рамі.',
    descEn: 'Monumental sacred relief inspired by Renaissance classics. Multi-layered intricate wood carving in an ornate baroque acanthus frame.',
    image: '/images/portfolio/madonna-child-relief.jpg',
    woodType: 'Масив дуба (доступно під замовлення: горіх, ясен, бук)',
    dimensions: '60 × 45 см',
  },
  {
    id: 'p-fairy-dresser',
    category: 'furniture',
    slug: 'fairy-carved-dresser',
    titleUk: 'Ексклюзивний комод «Казка Лісу» (з різьбленими феями)',
    titleEn: 'Bespoke Dresser «Forest Fairy» (Carved Mythic Credenza)',
    descUk: 'Авторський комод із масиву натурального дерева. Фасади оздоблені витонченою об’ємною різьбою лісових фей, центральний блок на 4 висувні шухляди з флористичними ручками, класичні канельовані пілястри та благородне текстурне патинування.',
    descEn: 'Bespoke solid wood sideboard dresser. Cabinet doors featuring intricate relief carvings of forest fairies, 4 central drawers with floral carved rosettes, fluted classical pilasters, and an antiqued patina finish.',
    image: '/images/portfolio/fairy-carved-dresser.jpg',
    woodType: 'Масив дуба / ясена з патинуванням (доступно під замовлення)',
    dimensions: '140 × 90 × 45 см (або за індивідуальними розмірами)',
  },
  {
    id: 'p-royal-wardrobe',
    category: 'furniture',
    slug: 'royal-carved-wardrobe',
    titleUk: 'Шафа «Королівська Спадщина» (з різьбленими медальйонами)',
    titleEn: 'Wardrobe «Royal Heritage» (Carved Medallion Cabinet)',
    descUk: 'Монументальна двостулкова шафа з масиву дерева в класичному стилі. Верхня секція зі скляними дверцятами та ротанговою сіткою, дві висувні шухляди з різьбленими розетками, нижні філенчасті дверцята з об\'ємними овальними медальйонами флоральних орнаментів. Різьблений карниз та фігурний цоколь.',
    descEn: 'Monumental two-door solid wood wardrobe in a classical style. Upper section with lattice glass doors, two drawers with carved rosettes, lower panelled doors featuring ornate oval floral medallions. Hand-carved cornice crown and shaped plinth base.',
    image: '/images/portfolio/royal-carved-wardrobe.jpg',
    woodType: 'Масив дуба / горіха з тонуванням (доступно під замовлення)',
    dimensions: '200 × 100 × 55 см (або за індивідуальними розмірами)',
  },
  {
    id: 'p-celtic-bench',
    category: 'rustic',
    slug: 'rustic-celtic-bench',
    titleUk: 'Лавка «Дух Полонини» (живий край з кельтським різьбленням)',
    titleEn: 'Bench «Highland Spirit» (Live-Edge with Celtic Carving)',
    descUk: 'Масивна авторська лавка з натурального слябу дерева зі збереженим живим краєм. Спинка прикрашена глибоким рельєфним кельтським орнаментом ручної роботи, ніжки — з натуральних гілок. Ідеальна для саду, тераси чи заміського будинку.',
    descEn: 'Massive handcrafted bench from a natural wood slab with preserved live edge. Backrest adorned with deep relief Celtic ornament, legs made from natural branches. Perfect for gardens, terraces, or country estates.',
    image: '/images/portfolio/rustic-celtic-bench.jpg',
    woodType: 'Масив дуба / ясена (живий край, натуральна текстура)',
    dimensions: '180 × 45 × 90 см (або за індивідуальними розмірами)',
  },
  {
    id: 'p-lighthouse-ship',
    category: 'carving',
    slug: 'lighthouse-ship-relief',
    titleUk: 'Барельєф «Вітрила Надії» (маяк і вітрильник)',
    titleEn: 'Bas-Relief «Sails of Hope» (Lighthouse & Galleon)',
    descUk: 'Панорамний морський барельєф ручної роботи в пишній різьбленій рамі з хвильовим та витковим орнаментом. Деталізована сцена — скелястий берег з маяком серед дерев та вітрильний корабель у бурхливому морі. Кожен елемент вирізьблений вручну з масиву дерева.',
    descEn: 'Panoramic maritime bas-relief in an ornate hand-carved frame with wave and rope motifs. Detailed scene — a rocky coastline with a lighthouse amid trees and a tall sailing ship on stormy seas. Every element hand-carved from solid wood.',
    image: '/images/portfolio/lighthouse-ship-relief.jpg',
    woodType: 'Масив дуба / ясена (доступно під замовлення)',
    dimensions: '70 × 50 см (або за індивідуальними розмірами)',
  },
  {
    id: 'p-nymph',
    category: 'carving',
    slug: 'nymph-grace-relief',
    titleUk: 'Барельєф «Народження Аврори» (Грація Німфи)',
    titleEn: "Bas-Relief «Birth of Aurora» (Nymph's Grace)",
    descUk: 'Витончене скульптурне панно в античній естетиці. Пластична жіноча постать у вихорі невагомих тканин та сонячних променів, вирізьблена в овальній ніші масиву дерева.',
    descEn: 'Graceful sculptural panel in classical antique aesthetics. Flowing feminine silhouette amidst light rays and drapery, carved inside an oval solid wood niche.',
    image: '/images/portfolio/nymph-grace-relief.jpg',
    woodType: 'Масив мореного дуба / горіха',
    dimensions: '50 × 30 см (або за індивідуальними розмірами)',
  },
  { id: 'p1', category: 'lighting', slug: 'pendent-oak', titleUk: 'Підвісна лампа з дуба', titleEn: 'Oak Pendant Lamp', descUk: 'Ручна різьба по мореному дубу. Унікальна форма, тепле світло.', descEn: 'Hand-carved aged oak. Unique form, warm glow.', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', woodType: 'Дуб морений' },
  { id: 'p2', category: 'carving', slug: 'relief-forest', titleUk: 'Рельєф «Ліс»', titleEn: 'Forest Relief', descUk: 'Об\'ємний рельєф із горіха, 120×80 см. Фотореалістичні деталі.', descEn: 'Walnut relief, 120×80 cm. Photorealistic detail.', image: 'https://images.unsplash.com/photo-1520923642038-b4259acecbd7?w=600&q=80', woodType: 'Горіх' },
  { id: 'p3', category: 'rustic', slug: 'live-edge-table', titleUk: 'Стіл Live Edge', titleEn: 'Live Edge Table', descUk: 'Слябовий стіл із живим краєм. Акація + метал.', descEn: 'Live edge slab table. Acacia + steel.', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80', woodType: 'Акація' },
  { id: 'p4', category: 'lighting', slug: 'wall-sconce', titleUk: 'Настінний бра', titleEn: 'Wall Sconce', descUk: 'Ясен + кована бронза. Ідеально для спальні.', descEn: 'Ash + forged bronze. Perfect for bedroom.', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80', woodType: 'Ясен' },
  { id: 'p5', category: 'carving', slug: 'eagle-sculpture', titleUk: 'Скульптура «Орел»', titleEn: 'Eagle Sculpture', descUk: 'Різьблений орел з груші, 45 см. Деталізована робота.', descEn: 'Pear wood eagle, 45 cm. Highly detailed.', image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&q=80', woodType: 'Груша' },
  { id: 'p6', category: 'furniture', slug: 'shelf-walnut', titleUk: 'Полиця з горіха', titleEn: 'Walnut Shelf', descUk: 'Навісна полиця з масиву горіха. Мінімалізм і природність.', descEn: 'Solid walnut floating shelf. Minimal and natural.', image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80', woodType: 'Горіх' },
  { id: 'p7', category: 'rustic', slug: 'barn-door', titleUk: 'Амбарні двері', titleEn: 'Barn Door', descUk: 'Розсувні двері в стилі рустик зі старого ясена.', descEn: 'Sliding barn-style door from reclaimed ash.', image: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?w=600&q=80', woodType: 'Ясен рустик' },
  { id: 'p8', category: 'furniture', slug: 'armchair-oak', titleUk: 'Крісло з дуба', titleEn: 'Oak Armchair', descUk: 'Масивне крісло з дуба та шкіри ручної роботи.', descEn: 'Solid oak and hand-stitched leather armchair.', image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80', woodType: 'Дуб' },
];
